export const ITEMS_PER_PAGE = 150;
export const ITEMS_PER_PAGE_LIST = [
  3,
  5,
  10,
  15,
  20,
  25,
  30,
  50,
  100,
  150,
  200,
  300,
  500,
];

export const PROGRESS = Object.freeze({
  Little: "〇 Little",
  Half: "◐ About half",
  Completed: "⬤ Completed",
});
export const SYMBOLS = Object.freeze({
  MILESTONE: "🔴",
});
export const PEOPLE_TYPES = Object.freeze({
  Client: "Client",
  Employee: "Employee",
  Supplier: "Supplier",
  SubContrator: "Sub-contrator",
});
export const CALENDAR_SETTING_COMBO = Object.freeze({
  None: "None",
  Combo1: "Combo 1",
  Combo2: "Combo 2",
  Combo3: "Combo 3",
  Combo4: "Combo 4",
  Combo5: "Combo 5",
});

export const SUBJECT_ITEMS = Object.freeze({
  Order: "Order",
  Quotation: "Quotation",
  Enquery: "Enquery",
});

export const STATUS_LIST_PROJECT = Object.freeze({
  PreManuStage: {
    status: "10 Pre-manu Stage",
    simplifiedStatus: "10PS",
    color: "blue-grey lighten-4",
  },
  PreManuStageCompleted: {
    status: "19 Pre-manu Stage Completed",
    simplifiedStatus: "19PC",
    color: "blue-grey lighten-4",
  },
  DesigingStage: {
    status: "20 Desiging Stage",
    simplifiedStatus: "20DS",
    color: "blue-grey lighten-4",
  },
  DesigingStageCompleted: {
    status: "29 Desiging Stage Completed",
    simplifiedStatus: "29DC",
    color: "blue-grey lighten-4",
  },
  ProductionStage: {
    status: "30 Production Stage",
    simplifiedStatus: "30PS",
    color: "blue-grey lighten-4",
  },
  ProductionStageCompleted: {
    status: "39 Production Stage Completed",
    simplifiedStatus: "39PC",
    color: "blue-grey lighten-4",
  },
  DeliveryStage: {
    status: "40 Delivery Stage",
    simplifiedStatus: "40DS",
    color: "blue-grey lighten-4",
  },
  DeliveryStageCompleted: {
    status: "49 Delivery Stage Completed",
    simplifiedStatus: "49DC",
    color: "blue-grey lighten-4",
  },
  InstallationStage: {
    status: "50 Installation Stage",
    simplifiedStatus: "50IS",
    color: "blue-grey lighten-4",
  },
  InstallationStageCompleted: {
    status: "59 Installation Stage Completed",
    simplifiedStatus: "59IC",
    color: "blue-grey lighten-4",
  },
  AllCompleted: {
    status: "60 All Completed",
    simplifiedStatus: "60AC",
    color: "red darken-1",
  },
  PaymentCompleted: {
    status: "69 Payment Completed",
    simplifiedStatus: "69PC",
    color: "blue-grey lighten-4",
  },
  Template: {
    status: "90 Template",
    simplifiedStatus: "90TP",
    color: "blue-grey lighten-2",
  },
  DailyOrder: {
    status: "98 Daily Order",
    simplifiedStatus: "98DO",
    color: "blue-grey lighten-2",
  },
  Archived: {
    status: "99 Archived",
    simplifiedStatus: "99AC",
    color: "blue-grey darken-3",
  },
});

export const STATUS_LIST_ROOM = Object.freeze({
  PreQuote: {
    status: "11 Pre-Quote",
    simplifiedStatus: "11PQ",
    color: "grey lighten-2",
  },
  Quoting: {
    status: "12 Quoting",
    simplifiedStatus: "12QI",
    color: "yellow lighten-3",
  },
  Quoted: {
    status: "13 Quoted",
    simplifiedStatus: "13QD",
    color: "grey lighten-2",
  },
  QuoteApproved: {
    status: "14 Quote Approved",
    simplifiedStatus: "14QA",
    color: "yellow lighten-1",
  },
  Pending: {
    status: "15 Pending",
    simplifiedStatus: "15PD",
    color: "grey lighten-2",
  },

  CheckMeasure: {
    status: "21 Check Measure",
    simplifiedStatus: "21CM",
    color: "green accent-1",
  },
  MaterialSpecs: {
    status: "22 Material Specs",
    simplifiedStatus: "22MS",
    color: "grey lighten-2",
  },
  Designing: {
    status: "23 Designing",
    simplifiedStatus: "23DS",
    color: "green accent-2",
  },
  PrepareCutlist: {
    status: "24 Prepare Cutlist",
    simplifiedStatus: "24PC",
    color: "grey lighten-2",
  },
  CutlistCompleted: {
    status: "25 Cutlist Completed",
    simplifiedStatus: "25CC",
    color: "green accent-3",
  },
  Scheduling: {
    status: "26 Scheduling",
    simplifiedStatus: "26SD",
    color: "grey lighten-2",
  },
  DepositInvoice: {
    status: "27 Deposit Invoice",
    simplifiedStatus: "27DI",
    color: "grey lighten-2",
  },
  DepositPaid: {
    status: "28 Deposit Paid",
    simplifiedStatus: "28DP",
    color: "green darken-1",
  },

  OrderingMaterial: {
    status: "31 Ordering Material",
    simplifiedStatus: "31OM",
    color: "grey lighten-2",
  },
  Cutting: {
    status: "32 Cutting",
    simplifiedStatus: "32CT",
    color: "light-blue lighten-4",
  },
  Assembling: {
    status: "33 Assembling",
    simplifiedStatus: "33AS",
    color: "grey lighten-2",
  },
  Stock: {
    status: "34 Stock",
    simplifiedStatus: "34ST",
    color: "grey lighten-2",
  },
  ProductionCompleted: {
    status: "35 Production Completed",
    simplifiedStatus: "35PC",
    color: "light-blue darken-1",
  },

  OrderDelivery: {
    status: "41 Order Delivery",
    simplifiedStatus: "41OD",
    color: "grey lighten-2",
  },
  DeliveryCompleted: {
    status: "42 Delivery Completed",
    simplifiedStatus: "42DC",
    color: "grey lighten-2",
  },

  Installation: {
    status: "51 Installation",
    simplifiedStatus: "51IT",
    color: "pink lighten-4",
  },
  InstallationCompleted: {
    status: "52 Installation Completed",
    simplifiedStatus: "52IC",
    color: "pink darken-1",
  },
  Fixup: {
    status: "53 Fixup",
    simplifiedStatus: "53FU",
    color: "grey lighten-2",
  },
  FixupCompleted: {
    status: "54 Fixup Completed",
    simplifiedStatus: "54FC",
    color: "grey lighten-2",
  },
});

export const STATUS_LIST_QUOTATION = Object.freeze({
  Quoting: {
    status: "1 Quoting",
    simplifiedStatus: "1QTI",
    color: "blue-grey lighten-5",
  },
  QuoteApproved: {
    status: "2 Quote Approved",
    simplifiedStatus: "2QAP",
    color: "blue-grey lighten-3",
  },
  Ordered: {
    status: "3 Ordered",
    simplifiedStatus: "3ORD",
    color: "blue-grey lighten-1",
  },
  Received: {
    status: "4 Received",
    simplifiedStatus: "4RCV",
    color: "light-blue lighten-4",
  },
  Stock: {
    status: "5 Stock",
    simplifiedStatus: "5STK",
    color: "light-blue lighten-2",
  },
  Invoiced: {
    status: "6 Invoiced",
    simplifiedStatus: "6INV",
    color: "light-blue darken-1",
  },
  Paid: { status: "7 Paid", simplifiedStatus: "7PAD", color: "teal accent-3" },
  Cancelled: {
    status: "9 Cancelled",
    simplifiedStatus: "9CCD",
    color: "teal darken-4",
  },
});

export const PART_TYPES = Object.freeze({
  Board: "Board",
  Edgetape: "Edgetape",
  Stone: "Stone",
  Glass: "Glass",
  Appliance: "Appliance",
  Hardware: "Hardware",
  Warehouse: "Warehouse",
  Machine: "Machine",
});

export const ROOM_NAMES = Object.freeze({
  Kitchen: "KIT-Kitchen",
  ButlerKitchen: "BKT-Butler Kitchen",
  WalkInPantry: "WIP-Walk in Pantry",
  Laundry: "LDR-Laundry",
  Storage: "STG-Storage",
  Linen: "LIN-Linen",
  Alfresco: "BBQ-Alfresco",
  Robe: "ROB-Robe",
  WalkInRobe: "WIR-Walk in Robe",
  TvUnit: "TVU-TV Unit",
  Vanity: "VAN-Vanity",
  ShavingCabinet: "SCT-Shaving Cabinet",
  VanityAndShaving: "VSC-Vanity and Shaving",
  FirePlace: "FPL-Fire Place",
  Study: "STD-Study",
  Garage: "GRG-Garage",
});

export const PERMISSION_OPTIONS = Object.freeze({
  InCCOfEmail: {
    label: "In CC of email",
    value: "InCCOfEmail",
    color: "black",
  },
  EditPermission: {
    label: "Edit Permission",
    value: "EditPermission",
    color: "error",
  },
  EditAll: {
    label: "Edit All(excludes permission)",
    value: "EditAll",
    color: "primary",
  },
  ReadAll: { label: "Read All", value: "ReadAll", color: "primary" },
  EditProject: {
    label: "Edit Project ",
    value: "EditProject",
    color: "success",
  },
  ReadProject: {
    label: "Read Project",
    value: "ReadProject",
    color: "success",
  },
  ReadOrderStock: {
    label: "Read QoR,Stock,Expense,Invoice",
    value: "ReadOrderStock",
    color: "accent",
  },
  EditClient: { label: "Edit Client", value: "EditClient", color: "secondary" },
  ReadClient: { label: "Read Client", value: "ReadClient", color: "secondary" },
  EditFile: { label: "Edit File", value: "EditFile", color: "warning" },
  ReadFile: { label: "Read File", value: "ReadFile", color: "warning" },
  EditRoom: { label: "Edit Room", value: "EditRoom", color: "info" },
  ReadRoom: { label: "Read Room", value: "ReadRoom", color: "info" },
  EditDatabase: {
    label: "Edit Database",
    value: "EditDatabase",
    color: "pink",
  },
  ReadDatabase: {
    label: "Read Database",
    value: "ReadDatabase",
    color: "pink",
  },
  ReadCalendar: {
    label: "Read Calendar",
    value: "ReadCalendar",
    color: "blue",
  },
});

export const FILE_TYPES = Object.freeze({
  OnsitePhoto: "11 Onsite photo - by pre-manu",
  QuoteDoc: "12 Quote Doc - by pre-manu",
  QuoteStone: "13 Quote Stone - by pre-manu",
  QuoteGlass: "14 Quote Glass - by pre-manu",
  QuoteTrades: "15 Quote Trades - by pre-manu",
  ConceptDesign: "16 Concept Design - by pre-manu",
  QuoteCommu: "17 Quote Commu - by pre-manu",
  QuoteOthers: "18 Quote Others - by pre-manu",
  ShopdrawingDesign: "21 Shopdrawing Design - by design",
  CutlistBeamsaw: "22 Cutlist Beamsaw - by design",
  CutlistCNC: "23 Cutlist CNC - by design",
  DesignCommu: "24 Design Commu - by design",
  DesignOthers: "25 Design Others - by design",
  Assembly: "31 Assembly - 拼装图 - by design",
  Hardware: "32 Hardware - 配件组装图 - by design",
  ProductionRecord: "32 Production Record - by manu",
  AppliancesDetails: "51 Appliances Details - 设备图 - by design",
  InstallationDrawing: "52 Installation Drawing - 安装图 - by design",
  InstallationPhoto: "53 Installation Photo - 安装进度照 - by install",
  DefectsPhoto: "54 Defects Photo - 维修收尾照 - by install",
  InstallationCommu: "55 Installation Commu - by install",
  Invoices: "61 Invoices - by financial",
  Others: "91 Others",
});

export const PROJECT_URGENCY = Object.freeze({
  Urgent: { urgency: "Urgent", color: "#D62305" },
  Important: { urgency: "Important", color: "" },
  Standard: { urgency: "Standard", color: "" },
  Awaiting: { urgency: "Awaiting", color: "" },
});

export default {
  MaxValue: 999999999,

  ProjectLabels: [
    "Multi Residential",
    "Residential",
    "Commercial",
    "Special",
    "Relationship",
    "Cash",
  ],
  ProjectDistance: ["Sydney Metro", "< 100KMs", "> 100 KMs"],
  ProjectTags: ["Pickup Only", "Delivery Only", "Supply and Install"],
  ProjectAccess: ["Lifts", "Hills", "Staircase", "Standard"],
  ProjectParkings: ["Offstreet", "Garage", "Loading Dock", "Difficult"],

  Languages: ["English", "Mandarin", "Cantonese"],

  defaultItem_Person: {
    type: "",
    givenname: "",
    surname: "",
    mobile: "",
    email: "",
    address: "",
    suburb: "",
    language: [],
    category: "",
    preference: null,
    company: "",
    abn: "",
    creditLimit: "",
    payTerm: "",
    status: "",
    outstanding: "",
    fax: "",
    salesRep: "",
    link: "",
    note: "",
    setting: "",
    permission: "",
    lastModifiedTime: "",
  },

  defaultItem_Quotation: {
    id: null,
    status: STATUS_LIST_QUOTATION.Quoting.status,
    roomId: null,
    partId: null,
    usingQty: null,
    buyingQty: 0,
    supplierId: null,
    subContractorId: null,
    subContractorQuo: null,
    subContractorQuoNo: "",
    note: "",
    position: "",
    link: "",
    orderNo: null,
    invoiceNo: null,
    invoiceDate: null,
    Material: "",
    Supplier: "",
    type: "",
  },

  FinishList: [
    "matt",
    "Abstract Createc",
    "abstract venettet",
    "Amaretto",
    "Ashgrain",
    "Btop Blank",
    "catalana Marble",
    "Chalk White",
    "createc",
    "Everest",
    "finegrain",
    "FM Colorpanel Particleboard MR",
    "FM E0 C/P MDF MR-Grain",
    "FM E0 Colorpanel MDF MR",
    "FM E0 Colorpanel MDF MR Gloss",
    "FM E0 Colorpanel MDF STD",
    "FM E0 Colorpanel PBrd MR",
    "FM E0 MDF MR FSC Mix 70%",
    "FM Particleboard Decorated-HPL",
    "Ice White",
    "legato",
    "LX Crystal Gloss MDF MR D/S",
    "LX Decorwood",
    "LX Decorwood-White",
    "LX E0 Crystal Gloss MDF MR D/S",
    "LX E0 Crystal Gloss MDF MR S/S",
    "LX E0 Decorwood",
    "LX E0 Decorwood FSC Mix 70%",
    "LX E0 Decorwood-Impressions",
    "LX E0 Decorwood-White",
    "LX E0 HPL MDF MR Veneer D/S",
    "LX E0 HPL MDF MR Veneer S/S",
    "LX E0 Lamiwood",
    "LX E0 Lamiwood FSC Mix 70%",
    "LX E0 Lamiwood Single Sided",
    "LX E0 Lamiwood-Impressions",
    "LX E0 Lamiwood-White",
    "LX E0 LW White FSC Mix 70%",
    "LX E0 MDF MR D/S Diamond Gloss",
    "LX E0 MDF MR HPL DS AbsolGrain",
    "LX E0 MDF MR HPL DS AbsolMatte",
    "LX E0 MDF MR HPL Magnetic",
    "LX E0 MDF MR HPL SS AbsolGrain",
    "LX E0 MDF MR HPL SS AbsolMatte",
    "LX E0 MDF MR Pan DS AbsolGloss",
    "LX E0 MDF MR Pan DS AbsolMatte",
    "LX E0 MDF MR Pan SS AbsolGloss",
    "LX E0 MDF MR Pan SS AbsolMatte",
    "LX E0 MDF MR S/S Diamond Gloss",
    "LX E0 MDF MR-Veneer",
    "LX E0 Particleboard MR DecImp",
    "LX E0 Silk MDF MR",
    "LX E0 Vertiboard MR",
    "LX E0 Vertibrd MR-Impressions",
    "LX MDF FG Decor Impre Blk Grp2",
    "LX MDF FG Decorated Black Grp2",
    "LX MDF FG Decorated Red Grp2",
    "LX MDF MR Select Grade",
    "LX Particleboard Decorated-HPL",
    "LX PB MR S/S Diamond Gloss",
    "LX Vertiboard MR",
    "LX Vertiboard MR-Impressions",
    "Mineral Quartz",
    "Mineral Sand",
    "Pietro Nero",
    "ravine",
    "satin",
    "Shadow Marble",
    "Shale Stone",
    "sheen",
    "Silvertone",
    "Slate",
    "Smoke Marble",
    "Snowdrift",
    "solid matt",
    "solid ultraglaze",
    "TE C/wd MR E0 FSC 100%",
    "TE C/wd MR E0 FSC Mix Credit",
    "TE Craftwood MR PEFC",
    "TE E0 Craftwood MR PEFC",
    "TE E0 Craftwood MR-Craftform",
    "TE E0 Craftwood STD PEFC",
    "TE E0 Craftwood STD-BackingBrd",
    "TE E0 MDF MR S/sided White",
    "TE E0 MDF MR Shelving Edged",
    "TE E0 MDF MR White",
    "TE E0 MDF STD White",
    "TE E0 MDFMR  White FSC Mix 70%",
    "TE E0 Particleboard MR",
    "TE Litecraft E1 FSC Mix",
    "TE MDF Coverboard InternL PEFC",
    "TE MDF MR White",
    "TE MDF STD Fireguard",
    "TE MDFMR E0 HighDens D/S Dec",
    "TE MDFMR E0 HighDens D/S White",
    "TE MDFMR E0 HighDens S/S Dec",
    "TE P/b Fireguard FSC MixCredit",
    "TE Particleboard MR",
    "TE PBrd MR-Preformed Ed",
    "Timber Print Matt",
    "ultraglaze",
    "venette",
    "White Pepper",
    "woodmatt",
  ],

  ColorList: [
    "Black",
    "Ghostgum",
    "Ligna",
    "Nat Burnish",
    "Natural",
    "Oak",
    "Pearl Refined",
    "Pewter",
    "Raw",
    "Red",
    "White",
    "Espresso Ligna",
    "Pearl Asphalt",
    "Pearl Iron",
    "Pearl Seal",
    "Pearl Warm",
    "Silver Strata",
    "Warm White",
    "18 White",
    "18.2 SeasonOak/WL",
    "Pearl Bliss",
    "Pearl Doe",
    "Pearl Flaxon",
    "Pearl Idyllic",
    "Pearl Lemon",
    "Pearl Mist",
    "Pearl Silver",
    "Pearl Snow",
    "Pearl Storm",
    "19.3 Sublime Teak",
    "24x12 PolarWhiteFlipped",
    "Pearl",
    "Pearl Manitoba",
    "Pearl Prestige",
    "Straight Grain",
    "Nat",
    "Pearl Deep",
    "AbGlo Ghostgum/White",
    "AbGlo OysterGrey/Gre",
    "AbGloss Ghostgum/Whi",
    "AbGloss Terril/Black",
    "AbGloss Tornado/Grey",
    "AbMat Pewter/Grey",
    "AbMat Surf/White",
    "AbMat Terril/Black",
    "AbsGlo Black/Black",
    "AbsGlo Terril/Black",
    "AbsGlo Tornado/Grey",
    "AbsGloss Black",
    "AbsGloss Black/Black",
    "AbsGloss Terril",
    "AbsGloss Tornado",
    "AbsMat Black",
    "AbsMat Black/Black",
    "AbsMat White",
    "AbsMat White/White",
    "Absolute Blanc",
    "ACraftwood",
    "Aged Ash",
    "Aged Ash/BL",
    "Aged Ash/Wh",
    "Aged Walnut",
    "Aged Walnut/Wh",
    "Airlie Blue",
    "Alabast Beech",
    "Alabast Gloss",
    "Alabaster",
    "Alabaster 0",
    "Alabaster 3600x1800",
    "Alabaster Antique",
    "Alabaster Antique White",
    "Alabaster Grey",
    "Alabaster Linewood",
    "Alabaster So",
    "Alabaster Teak",
    "Alabaster Walnut",
    "Alabaster White",
    "Alaskan",
    "Alaskan Beech",
    "Alaskan Linea",
    "Alaskan Maple",
    "Alaskan Nua",
    "Alaskan Oak",
    "Alaskan Smoke",
    "Alaskan WG",
    "Allure Ash",
    "Allure Ash/Whi",
    "Allure Ash/White",
    "Allure Oak",
    "Allure Oak/White",
    "Almendra",
    "Aloe",
    "Aloe Vera",
    "Alpaca",
    "Alpaca Limba",
    "Alpaca Linea",
    "Alpaca Oak",
    "Alpaca So",
    "Alpaca Teak",
    "Alpaca Vera",
    "Alpine Haze",
    "Alpine Mist",
    "Aluminium Flux Met",
    "Aluminium/Whi",
    "Amani Classico",
    "Amara",
    "Amaretto Stone",
    "Amari Oak",
    "Amari Vera",
    "Amazon Oak",
    "American Cherry",
    "American Oak",
    "American Oak MisMat",
    "American Oak'MRun'",
    "American Oak/Wh",
    "American Oak/Whi",
    "American Walnut",
    "American Walnut MisMat",
    "American White",
    "Angora So",
    "Antiq White",
    "Antique Refined Oak",
    "Antique Warm White",
    "Antique White",
    "Antique Wilnuna",
    "Antique Wiluna",
    "Antique Wiluna White",
    "Antler So",
    "Aquamarine",
    "Aquamarine Oak",
    "Aquamarine So",
    "Arcadia",
    "Aries",
    "Aries Smoke",
    "Aries So",
    "Arreis Red",
    "Artisan Beamwd/Wh",
    "Artisan Beamwood",
    "Ash",
    "Ash 3600mm",
    "Ash AntWillWhite",
    "Ash Ash White",
    "Ash Beech",
    "Ash Elm",
    "Ash Grey",
    "Ash Naturale",
    "Ash Oak",
    "Ash Palm",
    "Ash Teak",
    "ash white",
    "Ash Woodline",
    "AshWhit",
    "Asphalt",
    "Asphalt So",
    "Astral",
    "Athena",
    "Atisan Beamwood",
    "Atmosphere 100x22x2",
    "Autumn Oak",
    "Aveela Rigato",
    "Aveela Rigato/Wh",
    "Avenue",
    "Avenue Pri",
    "Avenue Valencia",
    "Avignon",
    "Avignon Beech",
    "Avignon Sky",
    "Avignon WalNuat",
    "Avignon Walnut",
    "Avignon White",
    "AvignoWalnut",
    "Azul Macaubus",
    "Baikal 2400x1200",
    "Baikal So",
    "Barcelona Cherry",
    "Bark So",
    "Basalt",
    "Basalt Pri",
    "Basalt White",
    "Batger",
    "Batger Clarity",
    "BatgerAsh Ash",
    "BatgerAsh White",
    "Battalion",
    "Battalion So",
    "Battalion White",
    "Batttalion",
    "Baye",
    "Baye 3600",
    "Baye 3600x1800",
    "Baye Linea",
    "Baye Maple",
    "Baye So",
    "Baye Teak",
    "Baye White",
    "Bayleaf",
    "Bayleaf So",
    "Bayleaf White",
    "Bayleaf/White Liner",
    "Beige",
    "Beige Oak",
    "Bianco Molasa",
    "Bianco Onix",
    "Birch 100x38x2",
    "Birch So",
    "Birchply WG",
    "Black Birchply",
    "Black Blue",
    "Black Finestone",
    "Black Fli",
    "Black Marble",
    "Black Multiplex",
    "Black Planked Pear",
    "Black S",
    "Black So",
    "Black Spotstick",
    "Black Spotstk",
    "Black Tulip",
    "Black White",
    "Black/BL",
    "Black/Black",
    "Black/White",
    "Black/White Liner",
    "Black460 So",
    "Blackbean",
    "Blackbean/White",
    "Blackbutt G",
    "Blackbutt/Whi",
    "Blackened",
    "Blackened Elm",
    "Blackened Legno",
    "Blackened Linewood",
    "Blackened Sublime Teak",
    "Blackened White",
    "BlackenedLinewd",
    "BlackenedLinewoo",
    "BlackenedLinewood",
    "BlackenLinewoo WG",
    "BlackenLinewood WG",
    "BlackLinewd",
    "Blackwood",
    "Blackwood 'MRun'",
    "Blackwood/BlkLi",
    "Blanco Naturale",
    "Bleached Elm",
    "Bleached Elm/Wh",
    "Bleached Honey",
    "Bleached Reed",
    "Bleached Walnut",
    "Bleached Wenge",
    "BleachWenge",
    "Bliss Cinder",
    "Bliss Shadow",
    "Bliss Shitake",
    "Blue Elm",
    "Blue Heaven",
    "Blue Moon",
    "Blue Oxide",
    "Bluegrass",
    "Bluegrass So",
    "Bodega Walnut",
    "Borghini Naturale",
    "Boxwood B",
    "Boxwood G",
    "Brandy Santos",
    "Brandy Santos/WL",
    "Brescia",
    "Brescia WG",
    "Bronx Beige",
    "Bronze/White Lin",
    "Bronzeworks",
    "Bronzeworks Heaven",
    "Bronzeworks Pri",
    "Brushed Nickel",
    "Brushed Silver",
    "Brushed Urban Wood",
    "Brushed Zinc",
    "Brushed Zinc/Dawn",
    "Brushwood",
    "Brushwood 100x22x1mm",
    "Brushwood WG",
    "Bud",
    "Bud So",
    "Burnished",
    "Burnished 3600mm",
    "Burnished Beech",
    "Burnished Oak",
    "Burnished Plum",
    "Burnished Wood",
    "Burnished Wood/Blk",
    "Burnished Wood/Whi",
    "BurnishedWood",
    "BurnishWood",
    "BurnishWood Grey",
    "BurnishWood/BurnWoo",
    "Burnt Strand",
    "C/wood",
    "Cafe Crema",
    "Cafe So",
    "Calacatta Blanco",
    "Calacatta Crema",
    "Calacatta Manhattan",
    "Calico",
    "Calico So",
    "Calm White",
    "Calypso Blue",
    "Caperberry",
    "Caperberry Pri",
    "Cappuccino So",
    "Cararra Marble",
    "Carrara",
    "Cashmere Pri",
    "Catalana Marble",
    "Ceniza",
    "CGM Crys",
    "Cha Fox Teakwood",
    "Cha Honey Elm",
    "Cha Natural Walnut",
    "Cha Raw Birchply",
    "Cha Rural Oak",
    "Cha Seasoned Oak",
    "Cha Sublime Teak",
    "Cha Whitewashed Oak",
    "Chalk Burnished Wood",
    "Chalk Elegant oak",
    "Chalk Polar",
    "Chalk White",
    "Chalked Oak",
    "Chalked Oak/WhiH",
    "Chalked Oak/White",
    "Chalked Slate",
    "Chalky",
    "Chalky Beech",
    "Chalky Oak/Blk",
    "Chalky Teak",
    "Chalky Wood",
    "Chamois",
    "Chamois Elm",
    "Chamois Oak",
    "Chamois S",
    "Chamois So",
    "Champagne So",
    "Char Blue",
    "Charcoa",
    "Charcoal",
    "Charcoal Beech",
    "Charcoal S",
    "Charcoal So",
    "Charcoal Tempo",
    "Charcoal/BL",
    "Charred Oak",
    "Charred Woodline",
    "Cherished Wood",
    "Cherry",
    "Cherry Riftwood",
    "Cherry Rifwood",
    "Cherry Walnut",
    "Cherry WG",
    "Chichi",
    "Chichi So",
    "China",
    "China Blue",
    "China Teak",
    "China White",
    "Chocolate Pear",
    "Cinder 100x21x1mm",
    "Cinnamon Ash",
    "Clamshell",
    "Clamshell So",
    "ClassBeige",
    "ClassBeige Blue",
    "ClassBeige Seal",
    "ClassBeige2400x1200",
    "Classic",
    "Classic Beech",
    "Classic Beige",
    "Classic Blue",
    "Classic Linewood",
    "Classic Oak",
    "Classic Riftwood",
    "Classic Teak",
    "Classic Walnut",
    "Classic Wood",
    "Clay Beech",
    "Clay Textile",
    "clear",
    "Clifton Walnut",
    "Cocoa Sand",
    "Como Rigato",
    "Como Rigato/Whit",
    "Concrete Formwood",
    "Concreto Avorio",
    "Concreto Naturale",
    "Coolum",
    "Coolum Beige",
    "Copycat",
    "Copycat Pri",
    "Coral",
    "Coral 0",
    "Coral Beech",
    "Coral So",
    "Country Cherry",
    "Coverboard",
    "Craftform",
    "Craftwood",
    "Craftwood 0",
    "Crys Anthracite",
    "Crys Onyx",
    "Crys Platinum",
    "Crys Quartz",
    "Crys Rubalite",
    "Crys Titanium",
    "Crys topaz",
    "Crys Tourmaline",
    "Crys Tungsten",
    "Crystal Diamond",
    "Crystal Diamond Met",
    "Crystal Lapis",
    "Crystal Palladium Met",
    "Crystal Platinum",
    "Crystal Titanium",
    "Crystal Tourmaline",
    "Crystal Tungsten",
    "Crystal White",
    "Cuban Wood",
    "Curley Birch",
    "Curly",
    "Curly Beige",
    "Curly Birch",
    "Curly Teak",
    "Curly Textile",
    "Curly Wood",
    "CurlyBi",
    "Cwood",
    "Cyclamen",
    "Cyclamen So",
    "D/S White",
    "Dansk",
    "Dansk Birch",
    "Dansk Maple",
    "Dansk Oak",
    "Dansk Riftwood",
    "Dansk Seal",
    "Dansk Teak",
    "Dansk Walnut",
    "Dansk Wood",
    "Dark Wenge/White",
    "Dark Wengeblock",
    "Dark Wengeblock/Blk",
    "Dark Wengeblock/White",
    "Dawn Grey",
    "Dawn Warm White",
    "Dec White",
    "Decor White",
    "Decortex",
    "Decortex Spotstick",
    "Decortex White",
    "Deep Anthracite",
    "Deep Sea",
    "Delana Oak",
    "Delana Oak/Wh",
    "Denim",
    "Denim 25x23x1mm",
    "Denim 25x42x1mm",
    "Denim 50x23x1mm",
    "Denim 50x42x1mm",
    "Denim So",
    "Des Aveela",
    "Des Blackbutt",
    "Des Blackbutt/Whi",
    "Des Buff",
    "Des Chalked",
    "Des Spotted",
    "Des Tasmanian",
    "Des TasmanOak/Whi",
    "Des Weathered",
    "Des.Firenze Rigato/Wh",
    "DesChaOak/Wh",
    "DesFirenzeRigato/Wh",
    "Design Allure",
    "Design Aveela Rigato",
    "Design Barley",
    "Design Biscotti",
    "Design Blackbean",
    "Design Blackbutt",
    "Design Blackwood",
    "Design Branchwood",
    "Design Buff",
    "Design Chalked",
    "Design Chalked Slate",
    "Design Como",
    "Design Halcyon",
    "Design Ironbark",
    "Design Jambire",
    "Design Livigno",
    "Design Matchstick",
    "Design Raisin",
    "Design Random",
    "Design Rimini",
    "Design Rosegum",
    "Design Savona Rigato",
    "Design Siam",
    "Design Spotted",
    "Design Tas",
    "Design Tasmanian",
    "Design Wild",
    "Design Wild Pecan",
    "Design Zulu",
    "Designed Barley",
    "Designed Blackbean",
    "Designed Blackwood",
    "Designed Jambire/White",
    "Designed Naturale",
    "Designed Wild",
    "Designed Zulu",
    "DesignPergugia Rigato",
    "DesWeathered Boxwood",
    "DiaGlo Ice",
    "DiaGlo Parchment/Black",
    "DiaGlo PolarWhite/Black",
    "DiaGloss Parchment",
    "DiaGloss Parchment/White",
    "DiaGloss PolarWhi/White",
    "DiaGloss Pumice",
    "DiaGloss White",
    "DiaGloss White/Black",
    "DiamGloss/Decortex Parchment",
    "Diamond",
    "Diamond Beige",
    "Diamond Blue",
    "DiamondGloss Black/Black",
    "DiamondGloss White/White",
    "Divine",
    "Divine Oak",
    "Doe Skin",
    "Dolce Vista Crema",
    "Domain",
    "Domain 100x21x2",
    "Domain 100x33x2",
    "Domain Maple",
    "Domain Oak",
    "Domain WG",
    "Dominio",
    "Dongwha",
    "Dt White",
    "E0 Pearl Vicenza",
    "Earth",
    "Earth 25x23x1mm",
    "Earth 25x42x1mm",
    "Earth 50x23x1mm",
    "Earth 50x42x1mm",
    "Earth So",
    "Ebony",
    "Ebony Bellezza",
    "Ebony Macassar",
    "Ebony Oak",
    "EbonyBellezza",
    "EbonyMacassa",
    "Echelon Maple",
    "Echelon Redwood",
    "Eclipse",
    "Eclipse Pri",
    "Eggplant",
    "Eggplant Redwood",
    "Eggplant So",
    "Eggshell",
    "Eggshell Linewood",
    "Eggshell Redwood",
    "Eggshell So",
    "Elagant Oak",
    "Electro Copper Met",
    "Electro Limegold Met",
    "Electro Pearl Met",
    "Elegance",
    "Elegance WG",
    "Elegant",
    "Elegant Oak",
    "Empire",
    "Empire So",
    "Enamel",
    "Enamel So",
    "Energise",
    "Energise So",
    "Energy Stream",
    "EnergyStrea",
    "EnergyStream",
    "EspressLigna",
    "Espresso",
    "Espresso 36x18",
    "Espresso Beige",
    "Espresso Oak",
    "Espresso So",
    "Espresso Walnut",
    "Espresso Wood",
    "EspressoLigna",
    "Euro Beech",
    "Even Eco",
    "Even Milkwood/White",
    "Even Saltwood",
    "EvenPlanked Oak",
    "EvenPlankOakGro/WhHPL",
    "Filament",
    "Filament Ligna",
    "Finesse Sand",
    "Finesse Stone",
    "Finesse Taupe",
    "Fini Blonde",
    "Fini Chocolate",
    "Fini Wenge",
    "Fino Buff",
    "Fino Buff/Blk",
    "Fino Buff/BlkL",
    "Fino Buff/White",
    "Flax",
    "Flax Beige",
    "Flax Birch",
    "Flax So",
    "Flaxon So",
    "Fli Alpaca",
    "Fli Aries",
    "Fli Ash White",
    "Fli Battalion",
    "Fli Black",
    "Fli Charcoal",
    "Fli Classic Beige",
    "Fli Curly Birch",
    "Fli Dansk Maple",
    "Fli Eggshell",
    "Fli Espresso",
    "Fli Fossil",
    "Fli Gunmetal",
    "Fli Ivory",
    "Fli Juicy",
    "Fli Mandarin",
    "Fli Met Satin",
    "Fli Milano Walnut",
    "Fli Moleskin",
    "Fli Natural Walnut",
    "Fli Olive",
    "Fli Olympia Blue",
    "Fli Olympia Yellow",
    "Fli Oyster Grey",
    "Fli Parchment",
    "Fli Platinum Micro",
    "Fli Polar White",
    "Fli Pumice",
    "Fli Rock Maple",
    "Fli Sarsen Grey",
    "Fli Seasoned Oak/Blk",
    "Fli Select Beech",
    "Fli Silver Grey",
    "Fli Stipple Hemp",
    "Fli Stipple Seal",
    "Fli White",
    "Fli Winter Sky",
    "Flinders Black",
    "Flint Alabaster",
    "Flint Alabster",
    "Flint Alpaca",
    "Flint Aries",
    "Flint Ash",
    "Flint Batger Blue",
    "Flint Battalion",
    "Flint Baye",
    "Flint Bayleaf",
    "Flint Black",
    "Flint Chalk White",
    "Flint Chamois",
    "Flint Charcoal",
    "Flint Classic",
    "Flint Coral",
    "Flint Denim",
    "Flint Diamond",
    "Flint Domain",
    "Flint Eggshell",
    "Flint Espresso",
    "Flint Flax",
    "Flint Fossil",
    "Flint Fox",
    "Flint Fresh Spring",
    "Flint Fresh Sprout",
    "Flint FreshSpring",
    "Flint Ghostgum",
    "Flint Green Slate",
    "Flint Grey",
    "Flint Gunmetal",
    "Flint Iceberg",
    "Flint Infinity",
    "Flint Juicy",
    "Flint Jute",
    "Flint Licorice Linea",
    "Flint Lustrous",
    "Flint Mandarin",
    "Flint Midnight",
    "Flint Milkwood",
    "Flint Moleskin",
    "Flint Moose",
    "Flint New",
    "Flint New Antique",
    "Flint NewGraphite",
    "Flint Oatmeal",
    "Flint Ocean Micro",
    "Flint OlympiaBlue",
    "Flint Oyster Grey",
    "Flint Oyster Linea",
    "Flint Parchment",
    "Flint Pearl Grey",
    "Flint Peruvian Clay",
    "Flint Pewter",
    "Flint Platinum Micro",
    "Flint Polar White",
    "Flint Possum",
    "Flint Pumice",
    "Flint Purely Purple",
    "Flint Red Cherry",
    "Flint Royal",
    "Flint Sarsen Grey",
    "Flint Seasoned Oak",
    "Flint Seed",
    "Flint Select Beech",
    "Flint Silver Ash",
    "Flint Silver Grey",
    "Flint Smoky Sapelle",
    "Flint Spinifex",
    "Flint Steel Blue",
    "Flint Stipple Seal",
    "Flint Sublime Teak",
    "Flint Super White",
    "Flint Tornado",
    "Flint Twine",
    "Flint Vanilla",
    "Flint Washboard",
    "Flint White",
    "Flint White Textile",
    "Flint Young Beech",
    "Flip PolarWhite",
    "Flipped PolarWhite",
    "Flipped White",
    "Flute Contour",
    "Formwood",
    "Formwood Pr",
    "Fossil",
    "Fossil 36x18",
    "Fossil Birch",
    "Fossil Maple",
    "Fossil So",
    "Fox",
    "Fox 3600x1800",
    "Fox So",
    "Fox Teakwood",
    "French",
    "French Cream",
    "French Navy",
    "French Navy/BLin",
    "Fresh",
    "Fresh Birch",
    "Fresh Maple",
    "Fresh Spring",
    "Fresh Sprout",
    "Fresh Wood",
    "Fudge Stream",
    "Gelsomino",
    "Gentle Beige",
    "Ghostgum 3600x1800",
    "Ghostgum So",
    "Ghostgum Spring",
    "Ghostgum White",
    "Glo Snowdrift",
    "Gloss Ant",
    "Gloss Antique",
    "Gloss Antler",
    "Gloss Ash",
    "Gloss Birch",
    "Gloss Bodega",
    "Gloss Brushed",
    "Gloss Brushwood",
    "Gloss Cappuccino",
    "Gloss Charcoal/Black",
    "Gloss Charcoal/White",
    "Gloss Charred",
    "Gloss Cinnamon",
    "Gloss Cuban",
    "Gloss Dawn",
    "Gloss Deep",
    "Gloss Finesse",
    "Gloss Fini",
    "Gloss Gentle",
    "Gloss Hotham",
    "Gloss Idyllic",
    "Gloss Iron",
    "Gloss Malibu",
    "Gloss Mist",
    "Gloss Mocha",
    "Gloss Mulga",
    "Gloss Natale",
    "Gloss Natural",
    "Gloss Oyster Linea",
    "Gloss Pumice/Black",
    "Gloss Refined",
    "Gloss Rock",
    "Gloss Silver",
    "Gloss Snow",
    "Gloss Snowdrift",
    "Gloss Streetlight",
    "Gloss Tassie",
    "Gloss Urban",
    "Gloss Vicenza",
    "Gloss Warm",
    "Gloss Warmwhite",
    "Gloss White",
    "Glossy White",
    "Glossy White/WhiLin",
    "Glossy White/White",
    "Glossy White/WL",
    "Golden Beech",
    "GR Des Como",
    "GR Design",
    "Graphite",
    "Graphite 100x45x2",
    "Graphite So",
    "Green",
    "Green Slate",
    "Green Slate/Whi",
    "Greige Ligna",
    "Greige Textile",
    "GREY",
    "Grey G",
    "Grey Kashmir",
    "Grey/WhiLin  ",
    "Greysto",
    "Greystone",
    "Greystone Pri",
    "Gris Naturale",
    "Gris Roca",
    "Gum/Whi",
    "Gunmetal",
    "Gunmetal 36x18",
    "Gunmetal Slate",
    "Gunmetal So",
    "Gunmetal Spring",
    "Habitat",
    "Habitat 2400x1200",
    "Habitat WG",
    "Hakata",
    "Hakata Pri",
    "Halcyon/White",
    "Hazelnut Spring",
    "Hazelnut Wood",
    "Hazelnut Wood/HazeWood",
    "HazelnutWood",
    "Hazelnutwood Sprout",
    "Hemp G2S",
    "Highland Ash",
    "Honey",
    "Honey Elm",
    "Honey Linewood",
    "Honey Oak",
    "Honey Walnut",
    "Hoop Pine",
    "Hotham Oak",
    "Hotham Shitake",
    "HPL Rural",
    "Husk",
    "Husk Teakwood",
    "Husk WG",
    "Hydra Mesh",
    "Ice",
    "Ice Quarstone",
    "Ice Veil",
    "Ice Veil/White",
    "Iceberg",
    "Iceberg So",
    "Icelandic AntWillWhite",
    "Icelandic Blue",
    "Idyllic",
    "Idyllic Oak",
    "Idyllic WG",
    "Imperial Grande",
    "Indian Sage",
    "Indian Smoke",
    "Infinity",
    "Infinity 200x21x2",
    "Infinity 200x33x2",
    "Infinity So",
    "Ink 2400x1200",
    "Ink So",
    "Iron Ore",
    "Ironbark/White",
    "Ironstone Pri",
    "Jalapeno",
    "Jalapeno So",
    "Jarrah",
    "Jarrah 'MRun'",
    "Jarrah Legno",
    "Jarrah Teakwood",
    "Jarrah WG",
    "Jericho",
    "Jericho  ",
    "Jericho Beech",
    "Jericho Birch",
    "Jericho Elm",
    "Jericho Legno",
    "Jericho Oak",
    "Jericho WG",
    "Juicy",
    "Juicy 3600mm",
    "Juicy 3600x1800",
    "Juicy Beige",
    "Juicy So",
    "Just",
    "Just Blue",
    "Just Legno",
    "Just Lilac",
    "Just Rose",
    "Jute",
    "Jute So",
    "Khaya Mahogany",
    "Knotty Ash",
    "lapis",
    "Lauro Crown/Whit",
    "Lava Elm",
    "Lava Grey",
    "Lava Rose",
    "Lemon Tree",
    "Lichen",
    "Lichen Blue",
    "Lichen So",
    "Lichen Washboard/White",
    "Licorice",
    "Licorice Birch",
    "Licorice Grey",
    "Licorice Linea",
    "Licorice Rose",
    "Licorice Teak",
    "LicoriceLine",
    "LicoriceLinea Sprout",
    "Light Wengeblock",
    "Light Wengeblock/Blk",
    "Light Wengeblock/White",
    "LightWenge/White",
    "Limba/WL Seductive",
    "Limed Ash",
    "Limestone",
    "Linewood",
    "Litecraft",
    "Livigno G",
    "Lustrous",
    "Lustrous Elm",
    "Lustrous Linea",
    "Lustrous Maple",
    "LustrousElm",
    "Mag Aluminium/WLin",
    "Mag Silver Brush/WhiteLin",
    "Malibu",
    "Malibu 100x22x1mm",
    "Malibu 2400x1200",
    "Malibu So",
    "Mandarin",
    "Mandarin 36x18",
    "Mandarin So",
    "Manitoba Figured",
    "Maple Woodline/WhiLin",
    "Marengo",
    "Marl",
    "Marl Beige",
    "MarlBei",
    "Mat Black/BL",
    "Mat Black/Black",
    "Mat Black/BlkLin",
    "Mat Denim/WhiLin",
    "Mat Denim/White",
    "Mat Earth/White",
    "Mat Stormcloud/Bl",
    "Mat Stormcloud/BlkLin",
    "Mat Surf/White",
    "Mat White/WhiLin",
    "Mat White/White",
    "Matchstick",
    "Matt Black",
    "Matt Black/WL",
    "Matt Golden Beech",
    "Matt SthWstJarrah",
    "Matt White",
    "Memphis Blue",
    "Memphis Green",
    "Memphis Red",
    "Met Brushed Aluminium",
    "Met Pewter Brush/WLin",
    "Metro Wood",
    "Midnight",
    "Midnight Beige",
    "Midnight So",
    "Milano",
    "Milano Beige",
    "Milano Birch",
    "Milano Elm",
    "Milano Ligna",
    "Milano Linea",
    "Milano Maple",
    "Milano Teak",
    "Milano Walnut",
    "Milkwood",
    "Milkwood Elm",
    "Milkwood Maple",
    "Milkwood Walnut",
    "Milkwood WG",
    "Millenium Oak",
    "Mist Grey",
    "Mix White",
    "Mocha Ash",
    "Mocha Firwood",
    "Mocha Oak",
    "Mocha So",
    "Mocha Strand",
    "Moleskin",
    "Moleskin 36x18",
    "Moleskin So",
    "Moleskin Walnut",
    "Moonstone",
    "Moonstone So",
    "Moose",
    "Moose Blue",
    "Moose Elm",
    "Moose Grey",
    "Moose Pr",
    "Moose Pri",
    "Moose S",
    "Moose So",
    "Moose Walnut",
    "Mt OysterGrey/WL",
    "Mulga So",
    "Multiplex WG",
    "Mushroom",
    "Mushroom Ligna",
    "Mushroom Linea",
    "MushroomLine",
    "Nat Aged Ash",
    "Nat Alaskan",
    "Nat Alpaca",
    "Nat Aquamarine",
    "Nat Ash White",
    "Nat Avignon Walnut",
    "Nat Basalt",
    "Nat Bayleaf",
    "Nat Black",
    "Nat Black RB",
    "Nat Blackened Elm",
    "Nat Blackened Linewood",
    "Nat BlackenedLinewood",
    "Nat Bleached Elm",
    "Nat Burnished Wood",
    "Nat CD Black/BlkLinTex",
    "Nat Classic Oak",
    "Nat Clay Textile",
    "Nat Curly Birch",
    "Nat Dansk Maple",
    "Nat Eggshell",
    "Nat Elegant Oak",
    "Nat Elgant Oak",
    "Nat Espresso Ligna",
    "Nat Fossil",
    "Nat Fox",
    "Nat Fox Teakwood",
    "Nat Fresh Spring",
    "Nat Honey Elm",
    "Nat Jarrah Legno",
    "Nat Jericho",
    "Nat Just Lilac",
    "Nat Just Rose",
    "Nat Lava Grey",
    "Nat Lemon",
    "Nat Licorice Linea",
    "Nat Lustrous Elm",
    "Nat Milano Walnut",
    "Nat Milkwood",
    "Nat Moose",
    "Nat Nat",
    "Nat Natural Walnut",
    "Nat Olive",
    "Nat Oyster Grey",
    "Nat Oyster Linea",
    "Nat Palisander",
    "Nat Parchment",
    "Nat Peacock",
    "Nat Pearl Grey",
    "Nat Peruvian Clay",
    "Nat Pesto Linea",
    "Nat Pillarbox",
    "Nat Polar",
    "Nat Polar White",
    "Nat Pumice",
    "Nat Raw Birchply",
    "Nat Rural Oak",
    "Nat Seasoned Oak",
    "Nat Select Beech",
    "Nat Silver Grey",
    "Nat Stipple Hemp",
    "Nat Stipple Seal",
    "Nat Stipple Smoke",
    "Nat Stormcloud",
    "Nat Super White",
    "Nat Tenderfoot",
    "Nat White",
    "Nat White Painted",
    "Nat White RB",
    "Nat White Textile",
    "Nat Winter Sky",
    "Natale Walnut",
    "Natural Aged Ash",
    "Natural Alaskan",
    "Natural Aloe",
    "Natural Aries",
    "Natural Ash",
    "Natural Baye",
    "Natural Beech",
    "Natural BurnishedWood",
    "Natural Charcoal",
    "Natural Classic",
    "Natural Clay",
    "Natural Curly",
    "Natural Dansk",
    "Natural Elegant",
    "Natural EspressoLigna",
    "Natural Iceberg",
    "Natural Jericho",
    "Natural Licorice",
    "Natural Licorice Linea",
    "Natural LicoriceLinea",
    "Natural Linea",
    "Natural Lustrous",
    "Natural Lustrous Elm",
    "Natural Mandarin",
    "Natural Mikwood",
    "Natural Milano",
    "Natural Milkwood",
    "Natural Moose",
    "Natural Multiplex",
    "Natural Natural Walnut",
    "Natural Noble",
    "Natural Nocturne",
    "Natural Oak",
    "Natural Oyster",
    "Natural PeruvianClay",
    "Natural Pillarbox",
    "Natural Polar White",
    "Natural PolarWhit",
    "Natural Pumice",
    "Natural Raw Birchply",
    "Natural RockMaple",
    "Natural Sarsen Grey",
    "Natural Seasoned",
    "Natural Seasoned Oak",
    "Natural Select",
    "Natural Silver Ash",
    "Natural SilverAsh",
    "Natural SmokySapelle",
    "Natural Stipple",
    "Natural Sublime",
    "Natural Sublime Teak",
    "Natural SwissPear",
    "Natural Tawny Linewood",
    "Natural TawnyLinewood",
    "Natural Teak",
    "Natural Walnut",
    "Natural White",
    "Natural Wood",
    "Natural Young",
    "Natural Zebrano",
    "Natural Zincworks",
    "NaturalZebran",
    "NaturalZebrano WG",
    "Navy/Bl",
    "Naxos",
    "Neo Cloud",
    "Neo Cloud/White",
    "Neo Cyclone",
    "Neo Tornado",
    "Neo Tornado/Blk",
    "Nero Astral",
    "New",
    "New Ant",
    "New Ant White",
    "New Antique",
    "New Antique White",
    "New Brushed Aluminium/White",
    "New Clarity",
    "New Graphite",
    "New Maple",
    "New Oak",
    "New Stainless",
    "New Stainless Steel",
    "New Teak",
    "New White",
    "New Zebrano",
    "NewAntiqueWhite",
    "NewAntW",
    "NewClarity",
    "NewGraphite",
    "Nieve White",
    "Noble",
    "Noble Cherry",
    "Nocturnal Oak/Black",
    "Nocturnal Oak/White",
    "Nocturne",
    "Nocturne Cherry",
    "Nocturne Graphite",
    "Nocturne Oak",
    "Nocturne So",
    "NocturneOak",
    "NocturnOak",
    "NocturnOak/Noct Oak",
    "Nombre",
    "Nordic Birch",
    "Nordic Elm",
    "Nordic Graphite",
    "Nordic Terra",
    "NordiTe",
    "Nu Silver Strata",
    "Nua Alaskan",
    "Nua Avignon",
    "Nua Baye",
    "Nua Black",
    "Nua BlackLinewood",
    "Nua Burnished Wood",
    "Nua BurnishedWood",
    "Nua Charred",
    "Nua Classic Oak",
    "Nua Domain",
    "Nua Espresso",
    "Nua EspressoLigna",
    "Nua Fossil",
    "Nua Grey",
    "Nua Idyllic",
    "Nua Jericho",
    "Nua Juicy",
    "Nua Lustrous Elm",
    "Nua Moose",
    "Nua NaturalZebran",
    "Nua New Graphite",
    "Nua Oak",
    "Nua Olympia Yellow",
    "Nua Parchment",
    "Nua Pillarbox",
    "Nua Polar White",
    "Nua Pumice",
    "Nua Season Oak",
    "Nua Seasoned Oak",
    "Nua Smoky Sapelle",
    "Nua Sublime  Teak",
    "Nua Sublime Teak",
    "Nua TawnyLinewood",
    "Nua Wenge",
    "Nua White",
    "Nuance Black",
    "Nuance Burnished Wood",
    "Nuance Espresso Ligna",
    "Nuance Millineum Oak",
    "Nuance Natural Walnut",
    "Nuance Oak",
    "Nuance Sublime Teak",
    "Nuance Wood",
    "Nuance Zincworks",
    "Oak  ",
    "Oak G",
    "Oak MRun",
    "Oak Red",
    "Oak WG",
    "Oak/Blk",
    "Oak/Blk HPL",
    "Oak/WhiH 12x24",
    "Oak/WhiLi",
    "Oatmeal",
    "Oatmeal Graphite",
    "Oatmeal So",
    "Ocean Micro",
    "Ocean Shimmer",
    "Ocean Terra",
    "Oiled Legno",
    "Oiled Legno/Wh",
    "Olive",
    "Olive So",
    "OlympBl",
    "OlympBlue",
    "Olympia",
    "Olympia Blue",
    "Olympia Clarity",
    "Olympia Elm",
    "Olympia Graphite",
    "Olympia Green",
    "Olympia Micro",
    "Olympia Orange",
    "Olympia Red",
    "Olympia Yellow",
    "Olympia Yellow/PolarWhi",
    "OlympiaOrang",
    "OlympiaOrange",
    "OlympiaRed Antique",
    "OlympiaYellow",
    "OlympOrange",
    "OlympYe",
    "Opal Grey",
    "Opal Yellow",
    "Organic Clarity",
    "Organic Green",
    "Organic So",
    "Oxide 100x22x2",
    "Oxidise Beamwood",
    "Oxidised Beamwood",
    "Oxidised Beamwood/Wh",
    "OysLinea",
    "OysteGr",
    "Oyster",
    "Oyster Elm",
    "Oyster Graphite",
    "Oyster Grey",
    "Oyster Grey/Gr",
    "Oyster Grey/Wh",
    "Oyster Grey/WhiLin",
    "Oyster Ligna",
    "Oyster Linea",
    "Oyster Maple",
    "Oyster Oak",
    "Oyster Textile",
    "Oyster Walnut",
    "Oyster Wenge",
    "Oyster White",
    "Oyster Yellow",
    "Oyster Zebrano",
    "OysterGrey/Gr",
    "OysterGrey/Grey",
    "OysterLine",
    "Painted Wood",
    "Palisander",
    "Palisander Linea",
    "Palisander WG",
    "Palisander Wood",
    "Palladium",
    "Paper",
    "Paper Ant",
    "Paper Bark",
    "Paper Grey",
    "PaperBark",
    "Paperbark Grey",
    "Papiro Chalk",
    "Papiro Kiln",
    "Papiro Mustard",
    "Parchm",
    "Parchm Bark",
    "Parchm Graphite",
    "Parchment",
    "Parchment 100x22x2",
    "Parchment 2400x1800",
    "Parchment Bark",
    "Parchment Clarity",
    "Parchment Graphite",
    "Parchment Grey",
    "Parchment Linea",
    "Parchment S",
    "Parchment So",
    "Parchment Spring",
    "Parchment/WL",
    "Pea Ink",
    "Pea Raw Birchply",
    "Peacock",
    "Peacock Oak",
    "Peacock So",
    "Peacock Yellow",
    "Pearl Angora",
    "Pearl Antique",
    "Pearl Antique Wiluna",
    "Pearl Antler",
    "Pearl AntWillWhit",
    "Pearl AntWillWhite",
    "Pearl Baikal",
    "Pearl Bark",
    "Pearl Beige Oak",
    "Pearl Birch",
    "Pearl Black",
    "Pearl Black 3600x1800",
    "Pearl Bliss Shitake",
    "Pearl Blue",
    "Pearl Blue Moon",
    "Pearl Bronx",
    "Pearl Bronx Beige",
    "Pearl Brushed",
    "Pearl Brushed Anthracite",
    "Pearl Brushed Blue",
    "Pearl Brushed Grey",
    "Pearl Brushed Nickel",
    "Pearl Brushed Silver",
    "Pearl Brushed Zinc/Dawn",
    "Pearl Bud",
    "Pearl Cafe",
    "Pearl Cappuccino",
    "Pearl Champagne",
    "Pearl Char",
    "Pearl Char Blue",
    "Pearl Charred Oak",
    "Pearl Charred Woodline",
    "Pearl Clifton Walnut",
    "Pearl Country Cherry",
    "Pearl Crystal",
    "Pearl Crystal White",
    "Pearl Dawn",
    "Pearl Dawn Grey",
    "Pearl Deep Anthracite",
    "Pearl DeepAnthrac",
    "Pearl DeepAnthracit",
    "Pearl Doe Skin",
    "Pearl Energise",
    "Pearl Fini",
    "Pearl Fini Blonde",
    "Pearl Fini Chocolate",
    "Pearl Fini Wenge",
    "Pearl Gentle",
    "Pearl Gentle Beige",
    "Pearl Golden Beech",
    "Pearl Graphite",
    "Pearl Grey",
    "Pearl Hotham Oak",
    "Pearl Icelac",
    "Pearl Indian",
    "Pearl Indian Sage",
    "Pearl Indian Smoke",
    "Pearl Ink",
    "Pearl Iron Oak",
    "Pearl Iron Ore",
    "Pearl Ironstone",
    "Pearl Malibu",
    "Pearl Malibu 2400x1200",
    "Pearl Matt Seal Grey",
    "Pearl Memp",
    "Pearl Memphis",
    "Pearl Memphis Blue",
    "Pearl Metro Wood",
    "Pearl Mist Grey",
    "Pearl Mocha",
    "Pearl Mulga",
    "Pearl Natural Oak",
    "Pearl Nordic Birch",
    "Pearl Opal",
    "Pearl Organic Green",
    "Pearl Pearl Ironstone",
    "Pearl Pearl Mist",
    "Pearl Planked Pear",
    "Pearl Pomegranate",
    "Pearl Prairie",
    "Pearl Prairie Beige",
    "Pearl Prima Graphite",
    "Pearl Refined Oak",
    "Pearl Rock Salt",
    "Pearl Sail",
    "Pearl Sail White",
    "Pearl Sarum",
    "Pearl Seal Grey",
    "Pearl Smoke Strand",
    "Pearl Snow Elm",
    "Pearl Snowdrift",
    "Pearl Soft Maple",
    "Pearl South West",
    "Pearl Stainless Steel/DoGrey",
    "Pearl Streetlight",
    "Pearl Sunflower",
    "Pearl Tas",
    "Pearl Tasmanian",
    "Pearl Tasmanian Ash",
    "Pearl Thistle",
    "Pearl Van",
    "Pearl Vel South",
    "Pearl Velvet Metro",
    "Pearl Velveteen",
    "Pearl VicenzaWalnut",
    "Pearl Walnut",
    "Pearl Warm White",
    "Pearl White",
    "Pearl Wiluna White",
    "Peat Linea",
    "Peat So",
    "Pelle Grigio",
    "Persimmon",
    "Persimmon So",
    "Peruvian",
    "Peruvian 2400",
    "Peruvian Clay",
    "Peruvian Clay/Black",
    "Peruvian Grey",
    "Peruvian Linea",
    "Peruvian Oak",
    "PeruvianClay/PeruvClay",
    "PeruviClay/White",
    "Pesto Clay",
    "Pesto Linea",
    "Petra Grigio",
    "Pewter Clay",
    "Pewter Grey",
    "Pewter So",
    "Pewter Spotstick",
    "Pewter/Grey",
    "Piedmont Cherry",
    "Pillabox",
    "Pillarbox",
    "Pillarbox Clay",
    "Pillarbox Linea",
    "Pillarbox So",
    "Pillarbox Walnut",
    "Pillarbox Yellow",
    "Pine Clear'MRun'D",
    "Pixel Tabac",
    "Plank Elm",
    "Planked Elm",
    "Planked Pear",
    "Planked Urban",
    "Planked Urban Oak",
    "PlankedUrbanOak",
    "Plantation",
    "Plantation Grey",
    "Plantation Oak'CGr'",
    "Plantation So",
    "Platinum",
    "Platinum Clay",
    "Platinum Lustre",
    "Platinum Micro",
    "Platinum Oak",
    "PlatinumMicro",
    "Plex Copper/BlkLin",
    "Plex Copper/WhiLin",
    "Polar",
    "Polar 3600",
    "Polar Blue",
    "Polar Graphite",
    "Polar Grey",
    "Polar Linewood",
    "Polar Micro",
    "Polar White",
    "Polar White RB",
    "Polar White/Whi",
    "Polar White/WhiLin",
    "PolarWh",
    "PolarWhi/PolWh",
    "PolarWhi/PolWhi",
    "PolarWhit Flipped",
    "PolarWhite",
    "PolarWhite Flipp",
    "PolarWhite Flipped",
    "PolarWhiteFlip",
    "PolarWhiteFlipped",
    "Polished Glossy White/WhiteLin",
    "Pomegranate",
    "Pomegranate So",
    "Poplar",
    "Poplar WG",
    "Posie",
    "Posie So",
    "Possum",
    "Possum So",
    "pPumice",
    "Prairie Beige",
    "Prestige Walnut",
    "Pri 100x22x2mm",
    "Pri 25x22x2mm",
    "Prima",
    "Prima White",
    "Prl White",
    "Pumice",
    "Pumice 2400",
    "Pumice 36x18",
    "Pumice Graphite",
    "Pumice Linea",
    "Pumice So",
    "Pumice White",
    "Pumice/White",
    "Pumice/WL",
    "Pure Marble",
    "Pure Mineralstone/White",
    "Purely Purple",
    "PurelyPurple",
    "Purple So",
    "QC DesignPergugia Rigato",
    "QC NAV Enviroven",
    "R",
    "Radiant Maple",
    "Rasberry",
    "Raspberry",
    "Raspberry So",
    "Raw Birchply",
    "Raw Cotton",
    "Raw Cotton/Wh",
    "Raw Linen",
    "Raw Multiplex",
    "Red Birchply",
    "Red Cherry",
    "Refined Oak",
    "Res Nat",
    "Retail",
    "Rigato/Bla",
    "Rigato/Blk",
    "Rigato/Whi",
    "Rimini Walnut",
    "Rimini Walnut/Wh",
    "Riv Alaskan",
    "Riv Ash White",
    "Riv Avignon Walnut",
    "Riv Baye",
    "Riv Blackened Elm",
    "Riv Bleached Wenge",
    "Riv Burnished Wood",
    "Riv Chalky Teak",
    "Riv Charcoal",
    "Riv Charred",
    "Riv Domain",
    "Riv Elegant Oak",
    "Riv Espresso",
    "Riv Espresso Ligna",
    "Riv Fossil",
    "Riv Honey Elm",
    "Riv Licorice Linea",
    "Riv Moose",
    "Riv Nat Walnut",
    "Riv Natural Walnut",
    "Riv Oak",
    "Riv Oyster Linea",
    "Riv Parchment",
    "Riv Polar White",
    "Riv Pumice",
    "Riv Refined Oak",
    "Riv Rural oak",
    "Riv Sapelle",
    "Riv Seasoned Oak",
    "Riv Smoky Sapelle",
    "Riv Sublime",
    "Riv Sublime Teak",
    "Riv White",
    "Riv Whitewashed Oak",
    "Riv Zincworks",
    "Riven Black",
    "Riven Oyster Linea",
    "Rock",
    "Rock Birchply",
    "Rock Cherry",
    "Rock Linea",
    "Rock Maple",
    "Rock Salt",
    "Rock Teak",
    "Rock White",
    "RockMap Clay",
    "Rosegum/White",
    "Royal",
    "Royal Integra",
    "Royal Maple",
    "Royal So",
    "Royal White",
    "Rural Oak",
    "Rural Walnut",
    "Rural Wenge",
    "Rural White",
    "Sail White",
    "Sakkara Ivory",
    "Sakkara Zincworks",
    "Salvage Planked",
    "Salvage Planked Elm",
    "Salvage Plnkd Elm",
    "SalvagePlank Elm/Wh",
    "Sandy Birch",
    "Sandy Oak",
    "Sandy Oak/BlkL",
    "Sandy Oak/Wh",
    "Sandy Oak/White",
    "Santorini",
    "Sapphire",
    "Sapporo Oak",
    "SarseGr",
    "Sarsen",
    "Sarsen Grey",
    "Sarsen Maple",
    "Sarsen White",
    "Sarum Grey",
    "Sarum Strand",
    "Sassi",
    "Sassi Integra",
    "Sassi So",
    "Sat Black",
    "Sat BlackenedLinewood",
    "Sat Steel/White",
    "Sat White",
    "Satin",
    "Satin Alaskan",
    "Satin Asphalt",
    "Satin Black",
    "Satin Charcoal",
    "Satin Decortext",
    "Satin Density",
    "Satin EbonyBellezza",
    "Satin EbonyMacassar",
    "Satin Elegance",
    "Satin EnergyStream",
    "Satin Espresso",
    "Satin Fossil",
    "Satin HazelnutWood",
    "Satin Heartwood",
    "Satin OlympOrange",
    "Satin Parchment",
    "Satin Pillarbox",
    "Satin Pumice",
    "Satin SatinHeartwood",
    "Satin SmokySapelle",
    "Satin Stipple Hemp",
    "Satin Stipple seal",
    "Satin Tanganyka",
    "Satin TawnyLinewood",
    "Satin Warm",
    "Satin White",
    "Satin white Spotstick",
    "Satin/Vel White",
    "Satin/Velvet White",
    "SatinHeartwoo",
    "Savona Rig",
    "Savona Rigato",
    "Savona Rigato/Wh",
    "Scandanavian Fir",
    "Scribe",
    "Scribe Pri",
    "Seal G2S",
    "Seal Grey",
    "Season Ash",
    "Season Ash/Blk",
    "Season Oak/WhiLin Glo",
    "Season Plnkd",
    "Seasond Plnkd Elm",
    "Seasoned",
    "Seasoned Ash",
    "Seasoned Ash/Whi",
    "Seasoned Birch",
    "Seasoned Grey",
    "Seasoned Husk",
    "Seasoned Integra",
    "Seasoned Linea",
    "Seasoned Maple",
    "Seasoned Oak",
    "Seasoned Oak G",
    "Seasoned Oak/WhiLin",
    "Seasoned Planked Elm",
    "Seasoned White",
    "SeasonedPlank Elm/Wh",
    "SeasonedPlanked Elm",
    "SeasoneOak",
    "Seductive",
    "Seductive Limba",
    "SeductiveLimb",
    "SeductiveLimba/Whi",
    "Seed",
    "Seed So",
    "SelecBe",
    "SelecBe Oak",
    "Select",
    "Select Beech",
    "Select Grey",
    "Select Integra",
    "Select Maple",
    "Select Oak",
    "Select White",
    "SelectBeec",
    "SelectBeech",
    "Sensation",
    "Sensation So",
    "Shadow/DawnGrey",
    "Shadowplay 100x22x2",
    "Sheer Mesh",
    "Siam G",
    "Siam/WhiHPL",
    "Siam/White",
    "Siam/White HPL",
    "Silk Alabaster",
    "Silk Aries",
    "Silk Battalion",
    "Silk Black",
    "Silk Brescia",
    "Silk Burnished Wood",
    "Silk Classic Beige",
    "Silk Domain",
    "Silk Ghostgum",
    "Silk Jericho",
    "Silk Licorice Linea",
    "Silk Moleskin",
    "Silk Moose",
    "Silk Mushroom Linea",
    "Silk New Antique",
    "Silk Oyster",
    "Silk Oyster Grey",
    "Silk Oyster Linea",
    "Silk Paper Bark",
    "Silk Parchment",
    "Silk Pesto Linea",
    "Silk Platinum Micro",
    "Silk Polar White",
    "Silk Pumice",
    "Silk Sarsen Grey",
    "Silk Silver Ash",
    "Silk Sublime Teak",
    "Silk Surf",
    "Silk Terril",
    "Silk Tornado",
    "Silk Washboard",
    "Silk White",
    "Silk Zincworks",
    "Silky Beech",
    "Silky Maple",
    "SilveGr",
    "silver",
    "Silver Ash",
    "Silver Beech",
    "Silver Grey",
    "Silver Oak",
    "Silver Riftwood",
    "Silver Rifwood",
    "Silver Shad/Dawn",
    "Silver Shadow",
    "Silver Zinc",
    "Slalom",
    "Slalom 2400x1200",
    "Slalom WG",
    "Slate/Bl",
    "Slate/Wh",
    "Smoke",
    "Smoke Melange",
    "Smoke Multiplex",
    "Smoke Multiplex Narrow",
    "Smoke So",
    "Smoke Strand",
    "Smoke/WhiteLiner",
    "Smoked Birchply",
    "Smoked Elm",
    "Smoked Oak",
    "Smoked Oak MisMat",
    "Smoked Oak/White",
    "Smoky",
    "Smoky Ash",
    "Smoky Husk",
    "Smoky Maple",
    "Smoky Sapelle",
    "SmokySapell",
    "SmokySapelle",
    "Snow Elm",
    "Snow Melange",
    "Snowdrift",
    "Snowdrift No Prot Film",
    "Snowdrift NoSpotSt",
    "Snowdrift So",
    "So 100x21x1mm",
    "So 100x22x2mm",
    "So 100x29x2",
    "So 25x22x2mm",
    "Soft Maple",
    "Sorrel",
    "Sorrel Grey",
    "Sorrel So",
    "South West",
    "South West Jarrah",
    "Sphinx",
    "Sphinx Grey",
    "Sphinx So",
    "Spinifex",
    "Spinifex So",
    "Spotstick",
    "Spotted Gum",
    "Spotted Gum/Blk",
    "SS",
    "Stainless St/Whi",
    "Stainless Stainless Steel/HPL",
    "Statuario Arabescato",
    "Statuario Venato",
    "Steel",
    "Steel Ash",
    "Steel Blue",
    "Steel Grey",
    "StipHemp/StipHem",
    "Stipp Hemp/StipHem",
    "StippGrass",
    "StippHemp",
    "Stipple",
    "Stipple Aquatic",
    "Stipple Beech",
    "Stipple Blue",
    "Stipple Bonsai",
    "Stipple Burn plum",
    "Stipple Burnish Plum",
    "Stipple Burnished",
    "Stipple Cocoa",
    "Stipple Grass",
    "Stipple Grey",
    "Stipple Hemp",
    "Stipple Lemongrass",
    "Stipple Linea",
    "Stipple Merlot",
    "Stipple Oak",
    "Stipple Sapelle",
    "Stipple Seal",
    "Stipple Seal/Black",
    "Stipple Smoke",
    "Stipple Sulphur",
    "Stipple Walnut",
    "StippleBonsai",
    "StippleHem",
    "StippleHemp",
    "StippleHemp/Black",
    "StippleSeal",
    "StipplHemp/White",
    "StipplSeal/White",
    "StipSeal/StipSea",
    "Stock Grey",
    "Stone Ash",
    "Stone Beige",
    "Stone Seal",
    "Storm 100x23x1",
    "Storm 100x42x1",
    "Storm 2400x1200",
    "Storm 3600x1800",
    "Storm So",
    "Stormcloud",
    "Stormcloud 25x23x1mm",
    "Stormcloud 25x42x1mm",
    "Stormcloud 50x23x1mm",
    "Stormcloud 50x42x1mm",
    "Stormcloud So",
    "Stormcloud/Blk",
    "Stormcloud/Storm",
    "Straight Grain Wenge",
    "Streetlight So",
    "StringyBark",
    "Stringybark Pri",
    "Sublime",
    "Sublime Ash",
    "Sublime Beech",
    "Sublime Hemp",
    "Sublime Maple",
    "Sublime Oak",
    "Sublime Sapelle",
    "Sublime Seal",
    "Sublime Smoke",
    "Sublime Teak",
    "Sublime Walnut",
    "Sublime Wenge",
    "SublimTeak",
    "Sunflower So",
    "Super White",
    "Surf",
    "Surf 25x23x1mm",
    "Surf 25x42x1mm",
    "Surf 50x23x1mm",
    "Surf 50x42x1mm",
    "Surf So",
    "Surf/White",
    "Swiss Hemp",
    "Swiss Pear",
    "Swiss Teak",
    "Tanganyka",
    "Tanganyka WG",
    "Tas Oak",
    "Tasmanian Ash",
    "Tasmanian Oak",
    "Tassie Oak",
    "Tawny Ant White",
    "Tawny Linea",
    "Tawny Linewood",
    "Tawny Seal",
    "Tawny Teak",
    "TawnyLinewd",
    "TawnyLinewoo",
    "TawnyLinewood",
    "TawnyLinewood WG",
    "TE White",
    "Teak",
    "Teak  ",
    "Teal",
    "Teal 2400x1200",
    "Teal So",
    "Tenderfoot",
    "Tenderfoot Hemp",
    "Tenderfoot Pear",
    "Tenderfoot So",
    "Terril",
    "Terril So",
    "Terril/Black",
    "Textile",
    "Textile/WhiLin  ",
    "Theron",
    "Thistle So",
    "Tornado",
    "Tornado 3600x1800",
    "Tornado Grey",
    "Tornado Seal",
    "Tornado So",
    "Tranquil Oak",
    "Tribal",
    "Tribal Hemp",
    "Tribal Oak",
    "Tribal Palm",
    "Triton",
    "Tunisan Stone",
    "Tuscan Pear",
    "Tuscan Walnut",
    "Twine",
    "Twine Beige",
    "Twine Hemp",
    "Twine Sapelle",
    "Twine So",
    "Urban Oak",
    "Urban Wood",
    "Vanilla",
    "Vanilla Grey",
    "Vanilla Palm",
    "Vanilla So",
    "Varona Pri",
    "Veil/PolWhite",
    "Vel Bliss Shitake",
    "Vel Malibu",
    "Vel New",
    "Vel Refined Oak",
    "Vel Straight Grain",
    "Vel Velveteen",
    "Vel Warm White",
    "Vel White",
    "Velvet",
    "Velvet Ash Woodline",
    "Velvet Black",
    "Velvet Brushed Silver",
    "Velvet BrushedSilver",
    "Velvet BrushSilv",
    "Velvet Brushwood",
    "Velvet Burnt Strand",
    "Velvet Char Blue",
    "Velvet Charred",
    "Velvet Charred Oak",
    "Velvet Charred Woodline",
    "Velvet Cherry",
    "Velvet Choc",
    "Velvet Choc Pear",
    "Velvet Cinnamon Ash",
    "Velvet Clifton",
    "Velvet Country Cherry",
    "Velvet Cuban Wood",
    "Velvet Dawn",
    "Velvet Euro",
    "Velvet Euro Beech",
    "Velvet EuroBeech",
    "Velvet Finesse Sand",
    "Velvet Finesse Stone",
    "Velvet Finesse Taupe",
    "Velvet Fini",
    "Velvet Fini Blonde",
    "Velvet Fini Chocolate",
    "Velvet Golden",
    "Velvet Golden Beech",
    "Velvet Hotham Oak",
    "Velvet Ironstone",
    "Velvet Jarrah",
    "Velvet KhayaMaho",
    "Velvet KhayaMahogany",
    "Velvet Lemon",
    "Velvet Lemon Tree",
    "Velvet Limed",
    "Velvet Limed Ash",
    "Velvet Manit",
    "Velvet Metro Wood",
    "Velvet Mocha Firwood",
    "Velvet Mocha Strand",
    "Velvet Natural",
    "Velvet Natural Oak",
    "Velvet New St/Steel/DawnGrey",
    "Velvet Nord",
    "Velvet Nordic Birch",
    "Velvet Papiro",
    "Velvet Pixel",
    "Velvet PlankedPe",
    "Velvet PlankedPea",
    "Velvet Prestige Walnut",
    "Velvet Rad",
    "Velvet Radiant",
    "Velvet Radiant Maple",
    "Velvet Refine",
    "Velvet Refined",
    "Velvet Refined Oak",
    "Velvet Rock",
    "Velvet Rock Salt",
    "Velvet Sarum Grey",
    "Velvet Sarum Strand",
    "Velvet Seal Grey",
    "Velvet Silv",
    "Velvet Silver Strata",
    "Velvet Soft",
    "Velvet Soft Maple",
    "Velvet South West",
    "Velvet SthWstJarr",
    "Velvet SthWstJarrah",
    "Velvet Storm",
    "Velvet StrGrainWenge",
    "Velvet StrGrnWen",
    "Velvet StrGrnWeng",
    "Velvet Tas",
    "Velvet Tasmanian",
    "Velvet Varona",
    "Velvet Velveteen",
    "Velvet Vice",
    "Velvet Warm White",
    "Velvet Waterstone",
    "Velvet White",
    "Velvet White Grade",
    "Velvet White Paint",
    "Velveteen So",
    "Venetian Walnut",
    "Vicenza Walnut",
    "Victorian Ash",
    "VIVID WHITE",
    "VL Brushed Aluminium",
    "VL Liner G",
    "Walnut",
    "Walnut B",
    "Walnut G",
    "Walnut Oak",
    "Walnut/W",
    "Wasabi 100x23x1.3",
    "Washboard",
    "Washboard Oak",
    "Washboard WG",
    "Washboard/Whi",
    "Washboard/White",
    "Washed Knotty",
    "Washed Knotty Ash",
    "Washed Oak",
    "Waxed Maple",
    "Waxed Oak",
    "Weath Boxwood",
    "Weath Boxwood/Blk",
    "Weath Boxwood/Wh",
    "Weathered Ash",
    "Weathered Ash/Wh",
    "Weathered Boxwood",
    "Wenge",
    "Wenge Linewood",
    "Wenge WG",
    "White Beech",
    "White Blue",
    "White Commodity",
    "White CW",
    "White Flip",
    "White Flipp",
    "White Flipped",
    "White FlipSelGr",
    "White G2S",
    "White Gloss",
    "White Grey",
    "White Hemp",
    "White Linen",
    "White Maple",
    "White Oak",
    "White Painted Wood",
    "White Pear",
    "White RB/White Liner",
    "White S",
    "White Satin",
    "White Select",
    "White Silver",
    "White Silver/White",
    "White So",
    "White SpotStFl",
    "White Spotstk",
    "White Teak",
    "White Tex Black",
    "White Textile",
    "White Valencia",
    "White Valencia/White",
    "White White",
    "White Zincworks",
    "White/Wh",
    "White/White",
    "White/WL",
    "White200 So",
    "WhiteSpSt",
    "WhiteVa",
    "WhiteValencia",
    "Whitewashed",
    "Whitewashed Knotty",
    "Whitewashed Linewood",
    "Whitewashed Oak",
    "Whitewashed Palm",
    "Whitewashed Seasoned Oak",
    "Whitewashed Sublime Teak",
    "Whitewashed Teak",
    "Whitewashed Veil",
    "Whitewashed Walnut",
    "Whitewashed White",
    "WhitewashedBirchply",
    "WhitewashedOak",
    "WhitewashedOak WG",
    "WhitewashOak",
    "Wild",
    "Wild Birch",
    "Wild Linewood",
    "Wild Pecan",
    "Wild Pecan/White",
    "Wiluna White",
    "Winter",
    "Winter Sky",
    "Wood  ",
    "Young",
    "Young 3600mm",
    "Young Beech",
    "Young Birch",
    "Young Grey",
    "Young Oak",
    "Young Palm",
    "Young Smoke",
    "YoungBe",
    "YoungBe Teak",
    "Zinc Lustre",
    "Zincworks",
    "Zincworks Beech",
    "Zincworks Oak",
    "Zincworks Pri",
    "Zincworks Teak",
  ],

  PositionList: [
    "All",
    "Base cab",
    "Wall cab",
    "Kicker",
    "Baulkhead",
    "Island panel",
    "Fridge panel",
    "Fridge cab",
    "Others",
  ],
};
